---
title: "GIAS links data"
format: 
  html:
    fig-width: 8
    fig-height: 5
    code-fold: true
    embed-resources: true
    self-contained-math: true
    toc: false
editor: visual
date: "`r Sys.Date()`"
---

```{R, include = FALSE}

library(dplyr)
library(stringr)
library(lubridate)
library(knitr)
library(kableExtra)
library(data.table)  
library(DT)

```

```{R, include = FALSE}
# load data


# Set up filepath ------------------------------------

FolderPath = paste0("C:/Users/cbousfield/OneDrive - Department for Education/Documents/9. Sep 2025/Hackathon/data/")

# Define the full path to CSV files
filePath_links <- paste0(FolderPath, "links_edubasealldata20250903.csv")
filePath_groups <- paste0(FolderPath, "groups.csv")
filePath_educase_all <- paste0(FolderPath, "edubasealldata20250903.csv")

# Read the CSV files
data_links <- read.csv(filePath_links, stringsAsFactors = FALSE)
data_groups <- read.csv(filePath_groups, stringsAsFactors = FALSE)
data_edubase_all <- read.csv(filePath_educase_all, stringsAsFactors = FALSE)


```

```{R, include = FALSE}

links_full_data <- data_links %>%
  rename("other_URN" = URN) %>%
  left_join(data_edubase_all, by = c("LinkURN" = "URN"))

```

```{R, include = FALSE}

check_name <- links_full_data %>%
  filter(LinkName != EstablishmentName)

# infant predecessor to primary - showing no previous junior/primary
Torriano_eg <- links_full_data %>%
  filter((str_starts(LinkName, "Torriano")))

# Hakin - infant junior primary
Hakin_eg <- links_full_data %>%
  filter((str_starts(LinkName, "Hakin")))

# check Hakin
check_Hakin <- data_edubase_all %>%
  filter((str_starts(EstablishmentName, "Hakin")))

# link established different to open and close dates
Abbey_hill_eg <- links_full_data %>%
  filter((str_starts(LinkName, "Abbey Hill Primary & Nursery")) 
         & (str_ends(LinkEstablishedDate, "2023")))

# fine
Trinity_eg <- links_full_data %>%
  filter((str_starts(LinkName, "Trinity Catholic College")))

summary_link_types <- links_full_data %>%
  group_by(LinkType) %>%
  summarise(count = n())


all_successors <- links_full_data %>%
  filter(str_starts(LinkType, "Successor"))

merged_successors <- all_successors %>%
  filter(LinkType == "Successor - merged")

amalgamated_successors <- all_successors %>%
  filter(LinkType == "Successor - amalgamated")


```

```{R, include = FALSE}
# predecessor - different Establishment link data to close date

all_predeccessors <- links_full_data %>%
  filter(str_starts(LinkType, "Predecessor"))

predeccessor_date_diffs_30_plus <- all_predeccessors %>%
  mutate(
    LinkEstablishedDate <- gsub("-", "", LinkEstablishedDate),
    LinkEstablishedDate = dmy(LinkEstablishedDate), 
    CloseDate <- gsub("-", "", CloseDate),
    CloseDate = dmy(CloseDate),
    date_diff = abs(difftime(LinkEstablishedDate, CloseDate, units = "days"))
  ) %>%
  filter(date_diff > 29)

num_predecessor_date_diff <- nrow(predeccessor_date_diffs_30_plus)

```

```{R, include = FALSE}
# school never linked or changed

#The summary figures may not be quite right - I done it on URN and not linkURN
 
#I was assuming that there would be the same amount of URNs as LINKURNs as there should be a version for predecessor and successor. 
#I think there are 29,929 different URNs and 29,845 different LinkURNs

not_linked <- anti_join(data_edubase_all, data_links, by = "URN")
num_not_linked <- nrow(not_linked)



#not_linked_urn <- anti_join(data_edubase_all, data_links, by = "URN")
#num_not_linked_urn <- nrow(not_linked_urn)

#not_linked_linkurn <- anti_join(data_edubase_all, data_links, by = c("URN" = "LinkURN"))
#num_not_linked_linkurn <- nrow(not_linked_linkurn)

#anti1 <- anti_join(not_linked_urn, not_linked_linkurn, by = c("URN" = "LinkURN"))
#anti2 <- anti_join(not_linked_linkurn, not_linked_urn, by = c("LinkURN" = "URN"))



check_not_linked_status <- not_linked %>%
  distinct(EstablishmentStatus..name.)
# 1.Open
# 2.Closed
# 3.Open, but proposed to close
# 4.Proposed to open

# 1.open
not_linked_and_open <- not_linked %>%
  filter(EstablishmentStatus..name. == "Open")

num_not_linked_and_open <- nrow(not_linked_and_open)

# 2. closed
not_linked_and_closed <- not_linked %>%
  filter(EstablishmentStatus..name. == "Closed")

num_not_linked_and_closed <- nrow(not_linked_and_closed)

# 3. open and proposed to close
not_linked_open_proposed_close <- not_linked %>%
  filter(EstablishmentStatus..name. == "Open, but proposed to close")

num_not_linked_open_proposed_close <- nrow(not_linked_open_proposed_close)

# 4.proposed to open
not_linked_proposed_open <- not_linked %>%
  filter(EstablishmentStatus..name. == "Proposed to open")

num_not_linked_proposed_open <- nrow(not_linked_proposed_open)

```

# schools not in the links dataset (note: needs checking, see comments)

There are `r num_not_linked` schools not in the links dataset. <br>`r num_not_linked_and_open` of these are open and are not proposed to close. <br>`r num_not_linked_open_proposed_close` of these are open but proposed to close. <br>`r num_not_linked_proposed_open` of these are proposed to open. <br>`r num_not_linked_and_closed` of these are closed.

# Number of link types

```{R, echo = FALSE, message = FALSE, warning = FALSE}

summary_link_types %>%
  datatable(rownames = FALSE)

```

# summary GIAS edubase all

```{R, include = FALSE}
# number of closure types in edubase_all

summary_closures <- data_edubase_all %>%
  group_by(ReasonEstablishmentClosed..name.) %>%
  summarise(count = n())

```

```{R, echo = FALSE, message = FALSE, warning = FALSE}

summary_closures %>%
  datatable(rownames = FALSE)

```

# Examples

Torriano = infant school became primary - no record of previous junior or primary <br>Abbey_hill_eg = dates not match (see predecessor date section) <br>Trinity_eg = fine. Just showing a school can be a predecessor of itself - academisation. <br>Hakin = ST: This school might be a good example, the junior and infant school merged to become a primary but the primary merged with another primary school. Only the second amalgamation is shown in the links data not the first ?

```{R, echo = FALSE, message = FALSE, warning = FALSE}

Torriano_eg %>%
  datatable(rownames = FALSE)
Abbey_hill_eg %>%
  datatable(rownames = FALSE)
Trinity_eg %>%
  datatable(rownames = FALSE)
check_Hakin %>%
  datatable(rownames = FALSE)
Hakin_eg %>%
  datatable(rownames = FALSE)

```

# Predecessors with different Establishment link data to close date (by 30+ days)

There are `r num_predecessor_date_diff` cases in the current links data where the Establishment link data differs by atleast 30 days to the closing data in the edubase_all data.

```{R, echo = FALSE, message = FALSE, warning = FALSE}

predeccessor_date_diffs_30_plus %>%
  
  # Convert all character columns to UTF-8
  mutate(across(where(is.character), ~ iconv(., from = "", to = "UTF-8", sub = "byte"))) %>%
  
  datatable(rownames = FALSE)

```

# infants and juniors to primary - JT

# primary and secondary to all through - ST

# all girls/boys to mixed - ST

# full_history

# links data - URN vs linkURN

```{R, include = FALSE}


# URNs not in LinkURN
urn_not_in_linkurn <- setdiff(unique(data_links$URN), unique(data_links$LinkURN))

# LinkURNs not in URN
linkurn_not_in_urn <- setdiff(unique(data_links$LinkURN), unique(data_links$URN))


urn_not_in_linkurn_df <- data.frame(URN = urn_not_in_linkurn)
linkurn_not_in_urn_df <- data.frame(LinkURN = linkurn_not_in_urn)

# random check
check_random_1a <- data_links %>%
  filter(URN == "111111")

check_random_1b <- data_links %>%
  filter(LinkURN == "111111")

check_random_2a <- data_links %>%
  filter(URN == "151595")

check_random_2b <- data_links %>%
  filter(LinkURN == "151595")

check_random_2c <- data_links %>%
  filter(LinkURN == "100152")

check_random_2d <- data_links %>%
  filter(URN == "100152")

```

```{R, echo = FALSE, message = FALSE, warning = FALSE}
```
